/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConfirmarRouteImport } from './routes/confirmar'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTurnosRouteImport } from './routes/app.turnos'
import { Route as AppPlanoRouteImport } from './routes/app.plano'
import { Route as AppOcorrenciasRouteImport } from './routes/app.ocorrencias'
import { Route as AppNotasRouteImport } from './routes/app.notas'
import { Route as AppMembrosRouteImport } from './routes/app.membros'
import { Route as AppHistoricoRouteImport } from './routes/app.historico'
import { Route as AppFolgasRouteImport } from './routes/app.folgas'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppCargosRouteImport } from './routes/app.cargos'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api.webhooks.stripe'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarRoute = ConfirmarRouteImport.update({
  id: '/confirmar',
  path: '/confirmar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTurnosRoute = AppTurnosRouteImport.update({
  id: '/turnos',
  path: '/turnos',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanoRoute = AppPlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => AppRoute,
} as any)
const AppOcorrenciasRoute = AppOcorrenciasRouteImport.update({
  id: '/ocorrencias',
  path: '/ocorrencias',
  getParentRoute: () => AppRoute,
} as any)
const AppNotasRoute = AppNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AppRoute,
} as any)
const AppMembrosRoute = AppMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppFolgasRoute = AppFolgasRouteImport.update({
  id: '/folgas',
  path: '/folgas',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCargosRoute = AppCargosRouteImport.update({
  id: '/cargos',
  path: '/cargos',
  getParentRoute: () => AppRoute,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/confirmar': typeof ConfirmarRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pagamento': typeof PagamentoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/app/cargos': typeof AppCargosRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/folgas': typeof AppFolgasRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/membros': typeof AppMembrosRoute
  '/app/notas': typeof AppNotasRoute
  '/app/ocorrencias': typeof AppOcorrenciasRoute
  '/app/plano': typeof AppPlanoRoute
  '/app/turnos': typeof AppTurnosRoute
  '/app/': typeof AppIndexRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmar': typeof ConfirmarRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pagamento': typeof PagamentoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/app/cargos': typeof AppCargosRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/folgas': typeof AppFolgasRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/membros': typeof AppMembrosRoute
  '/app/notas': typeof AppNotasRoute
  '/app/ocorrencias': typeof AppOcorrenciasRoute
  '/app/plano': typeof AppPlanoRoute
  '/app/turnos': typeof AppTurnosRoute
  '/app': typeof AppIndexRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/confirmar': typeof ConfirmarRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pagamento': typeof PagamentoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/app/cargos': typeof AppCargosRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/folgas': typeof AppFolgasRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/membros': typeof AppMembrosRoute
  '/app/notas': typeof AppNotasRoute
  '/app/ocorrencias': typeof AppOcorrenciasRoute
  '/app/plano': typeof AppPlanoRoute
  '/app/turnos': typeof AppTurnosRoute
  '/app/': typeof AppIndexRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/confirmar'
    | '/contato'
    | '/login'
    | '/onboarding'
    | '/pagamento'
    | '/privacidade'
    | '/suporte'
    | '/termos'
    | '/app/cargos'
    | '/app/configuracoes'
    | '/app/folgas'
    | '/app/historico'
    | '/app/membros'
    | '/app/notas'
    | '/app/ocorrencias'
    | '/app/plano'
    | '/app/turnos'
    | '/app/'
    | '/api/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirmar'
    | '/contato'
    | '/login'
    | '/onboarding'
    | '/pagamento'
    | '/privacidade'
    | '/suporte'
    | '/termos'
    | '/app/cargos'
    | '/app/configuracoes'
    | '/app/folgas'
    | '/app/historico'
    | '/app/membros'
    | '/app/notas'
    | '/app/ocorrencias'
    | '/app/plano'
    | '/app/turnos'
    | '/app'
    | '/api/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/confirmar'
    | '/contato'
    | '/login'
    | '/onboarding'
    | '/pagamento'
    | '/privacidade'
    | '/suporte'
    | '/termos'
    | '/app/cargos'
    | '/app/configuracoes'
    | '/app/folgas'
    | '/app/historico'
    | '/app/membros'
    | '/app/notas'
    | '/app/ocorrencias'
    | '/app/plano'
    | '/app/turnos'
    | '/app/'
    | '/api/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ConfirmarRoute: typeof ConfirmarRoute
  ContatoRoute: typeof ContatoRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PagamentoRoute: typeof PagamentoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SuporteRoute: typeof SuporteRoute
  TermosRoute: typeof TermosRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar': {
      id: '/confirmar'
      path: '/confirmar'
      fullPath: '/confirmar'
      preLoaderRoute: typeof ConfirmarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/turnos': {
      id: '/app/turnos'
      path: '/turnos'
      fullPath: '/app/turnos'
      preLoaderRoute: typeof AppTurnosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plano': {
      id: '/app/plano'
      path: '/plano'
      fullPath: '/app/plano'
      preLoaderRoute: typeof AppPlanoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ocorrencias': {
      id: '/app/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/app/ocorrencias'
      preLoaderRoute: typeof AppOcorrenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notas': {
      id: '/app/notas'
      path: '/notas'
      fullPath: '/app/notas'
      preLoaderRoute: typeof AppNotasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/membros': {
      id: '/app/membros'
      path: '/membros'
      fullPath: '/app/membros'
      preLoaderRoute: typeof AppMembrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/historico': {
      id: '/app/historico'
      path: '/historico'
      fullPath: '/app/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/folgas': {
      id: '/app/folgas'
      path: '/folgas'
      fullPath: '/app/folgas'
      preLoaderRoute: typeof AppFolgasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cargos': {
      id: '/app/cargos'
      path: '/cargos'
      fullPath: '/app/cargos'
      preLoaderRoute: typeof AppCargosRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCargosRoute: typeof AppCargosRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppFolgasRoute: typeof AppFolgasRoute
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppMembrosRoute: typeof AppMembrosRoute
  AppNotasRoute: typeof AppNotasRoute
  AppOcorrenciasRoute: typeof AppOcorrenciasRoute
  AppPlanoRoute: typeof AppPlanoRoute
  AppTurnosRoute: typeof AppTurnosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCargosRoute: AppCargosRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppFolgasRoute: AppFolgasRoute,
  AppHistoricoRoute: AppHistoricoRoute,
  AppMembrosRoute: AppMembrosRoute,
  AppNotasRoute: AppNotasRoute,
  AppOcorrenciasRoute: AppOcorrenciasRoute,
  AppPlanoRoute: AppPlanoRoute,
  AppTurnosRoute: AppTurnosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ConfirmarRoute: ConfirmarRoute,
  ContatoRoute: ContatoRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PagamentoRoute: PagamentoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SuporteRoute: SuporteRoute,
  TermosRoute: TermosRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
